### ISSUE TITLE
encoding errors with some weird characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#71]
```
What steps will reproduce the problem?
1. try to scrap Choplifter with giantbomb scraper

at position 711, the character '\xf8' cant be encoded again. This is not a 
romcollectionbrowser error, insted is an error from the interpreter version 
used by xbmc, they need to update it (they will in eden release if you follow 
their trac.)


```

Original issue reported on code.google.com by `jimy...@gmail.com` on 22 Jan 2011 at 12:06

**Comment by bruny** [comment]
This specific issue appears to be related to the ø character in the publisher name Brøderbund.

Appears to be fixed in recent Kodi versions (I tested on Isengard, adding Choplifter!.dsk as an AppleII rom and scraping Giantbomb).

Logs (/Users/<user>/Library/Logs/kodi.log on Mac) shows:
22:46:45 T:123145303453696  NOTICE: RCB_INFO: resultKey: Developer
22:46:45 T:123145303453696  NOTICE: RCB_INFO: resultValue: ['Br\xc3\xb8derbund Software, Inc.']

On the RCB Game Info dialog, the Developer Brøderbund is displayed correctly.
